# Sorting, Counting, Querying

We often have a large dataset but we are only interested in smaller sections of it.

Or we want to sort from largest to smallest.

Or perhaps we want to know how many instances of some value there is in the data.

Tonight we finally move beyond the basics to see the start of data analysis.

## Import libraries

In [2]:
## import libraries
import pandas as pd

## Upload Olympics datasets to this notebook.

### Import ```olympics-summer.csv``` and store in a dataframe called ```dfs``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-summer.csv">link</a>).


### Import ```olympics-winter.csv``` and store in a dataframe called ```dfw``` (<a href="https://raw.githubusercontent.com/sandeepmj/datasets/main/olympics-winter.csv">link</a>).

In [6]:
## import summer data
dfs = pd.read_csv("olympics-summer.csv")

In [7]:
## import winter data
dfw = pd.read_csv("olympics-winter.csv")

## Get a sense of the data

In [8]:
## SUMMER
## what exactly do we have: columns, datatypes, etc.

dfs.info()

<class 'pandas.DataFrame'>
RangeIndex: 222552 entries, 0 to 222551
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ID            222552 non-null  int64
 1   Athlete Name  222552 non-null  str
 2   Sex           222552 non-null  str
 3   Age           213363 non-null  float64
 4   Height        170695 non-null  float64
 5   Weight        168698 non-null  float64
 6   Team          222552 non-null  str
 7   NOC           222552 non-null  str
 8   Year          222552 non-null  int64
 9   City          222552 non-null  str
 10  Sport         222552 non-null  str
 11  Event         222552 non-null  str
 12  Medal         34088 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 22.1 MB

In [9]:
## WINTER
## what exactly do we have: columns, datatypes, etc.

dfw.info()

<class 'pandas.DataFrame'>
RangeIndex: 48564 entries, 0 to 48563
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            48564 non-null  int64
 1   Athlete Name  48564 non-null  str
 2   Sex           48564 non-null  str
 3   Age           48279 non-null  float64
 4   Height        40250 non-null  float64
 5   Weight        39543 non-null  float64
 6   Team          48564 non-null  str
 7   NOC           48564 non-null  str
 8   Year          48564 non-null  int64
 9   City          48564 non-null  str
 10  Sport         48564 non-null  str
 11  Event         48564 non-null  str
 12  Medal         5695 non-null   str
dtypes: float64(3), int64(2), str(8)
memory usage: 4.8 MB

## SKIPPED AND MISSED TILL 2:47 PRETTY MUCH BECAUSE OF COMP BEING FULL AND FREEZING AND CRAPPING OUT

## test

In [12]:
x = 10
x

## This is an ASSIGNMENT. One = sign means you are assigning something.

10

In [14]:
## Two equal signs are checking for equality. 

x == 10

True

In [17]:
dfw.columns

Index(['ID', 'Athlete Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC',
       'Year', 'City', 'Sport', 'Event', 'Medal'],
      dtype='str')

In [18]:
## are the two column headers identical? 

dfw.columns == dfs.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [21]:
## Join winter and summer dataframes together into a datafram called

## because it's more than one value, it has to be a LIST (so square brackets)
df = pd.concat([dfs,dfw])
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48559,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48560,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
48561,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
48562,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
48563,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

In [24]:
## BUT look and see that 271,116 rows × 13 columns should be right. But the index (first column) shows 48,563. 
## So it ignored the attached indexes, which doesn't make sense. 

## you want to ignore index!

df = pd.concat([dfs,dfw], ignore_index = True )
df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
0,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
1,1724,Aristidis Akratopoulos,M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
2,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Tennis,Tennis Men's Singles,NaN
3,1725,"Konstantinos ""Kostas"" Akratopoulos",M,NaN,NaN,NaN,Greece-3,GRE,1896,Athina,Tennis,Tennis Men's Doubles,NaN
4,4113,Anastasios Andreou,M,NaN,NaN,NaN,Greece,GRE,1896,Athina,Athletics,Athletics Men's 110 metres Hurdles,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

In [ ]:
## This looks right!

In [25]:
# Query to subset
## Create smaller datasets with only the info you want

## df.query("ColumnName == 'some_value'")

In [26]:
## return df that holds only Sochi data

df.query("City == 'Sochi'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
266225,16,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Finland,FIN,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
266226,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN
266227,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Men's Singles,NaN
266228,145,Jeremy Abbott,M,28.0,175.0,70.0,United States,USA,2014,Sochi,Figure Skating,Figure Skating Mixed Team,Bronze
266229,463,Agnese boltia,F,17.0,166.0,60.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Super G,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135485,Stepan Olegovich Zuyev,M,25.0,189.0,90.0,Russia,RUS,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
271112,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
271113,135500,Kristaps Zvejnieks,M,21.0,185.0,87.0,Latvia,LAT,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
271114,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271115,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN

In [27]:
## One of our prompts should always telling Claude etc that "if it needs to create a subset, always create a Pandas query." 
## Query is a newer pandas tool

In [29]:
df.query("Sport == 'Ice Hockey'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
12651,5429,Karl Wilhelm Konrad Arwe (Andersson-),M,22.0,NaN,NaN,Sweden,SWE,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
12775,10216,"Robert John ""Bobby"" Benson",M,25.0,167.0,61.0,Canada,CAN,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold
12916,13265,"Raymond Leroy ""Ray"" Bonney",M,28.0,175.0,81.0,United States,USA,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
13075,16648,Hjalmar Eric Wilhelm Burman,M,22.0,NaN,NaN,Sweden,SWE,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
13085,17100,"Jacob Walter ""Wally"" Byron",M,35.0,180.0,65.0,Canada,CAN,1920,Antwerpen,Ice Hockey,Ice Hockey Men's Ice Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
270998,133605,Tom Zborsk,M,26.0,183.0,88.0,Slovakia,SVK,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
271043,134391,Carl Henrik Zetterberg,M,33.0,183.0,86.0,Sweden,SWE,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,Silver
271080,134924,Marek idlick,M,37.0,180.0,85.0,Czech Republic,CZE,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
271100,135255,Julia Zorn,F,24.0,170.0,73.0,Germany,GER,2014,Sochi,Ice Hockey,Ice Hockey Women's Ice Hockey,NaN
271108,135365,Mats Andr Zuccarello-Aasen,M,26.0,171.0,74.0,Norway,NOR,2014,Sochi,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN

In [31]:
## We are now going to test searching for a name with a space in it (which pandas doesnt like spaces)

# will break

df.query("Athlete Name == 'Forough Abbasi'")

SyntaxError: invalid syntax (<unknown>, line 1)

In [33]:
df.query("`Athlete Name` == 'Forough Abbasi'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
266226,126,Forough Abbasi,F,20.0,164.0,58.0,Iran,IRI,2014,Sochi,Alpine Skiing,Alpine Skiing Women's Slalom,NaN

In [38]:
# Query by dates
## find all the 1900 competitions

df.query("Year == 1900")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
380,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
381,133,Franz Abb,M,NaN,NaN,NaN,Germany,GER,1900,Paris,Gymnastics,Gymnastics Men's Individual All-Around,NaN
382,150,Margaret Ives Abbott (-Dunne),F,23.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,Gold
383,151,Mary Perkins Ives Abbott (Perkins-),F,42.0,NaN,NaN,United States,USA,1900,Paris,Golf,Golf Women's Individual,NaN
384,404,"Louis Grenville ""Lou"" Abell",M,15.0,NaN,NaN,Vesper Boat Club,USA,1900,Paris,Rowing,Rowing Men's Coxed Eights,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,131733,William Hayden Wright,M,NaN,NaN,NaN,A North American Team,USA,1900,Paris,Polo,Polo Men's Polo,Bronze
2312,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's Foil, Masters, Individual",NaN
2313,133574,Henri Yvon,M,NaN,NaN,NaN,France,FRA,1900,Paris,Fencing,"Fencing Men's epee, Masters, Individual",NaN
2314,133807,Pyotr Antonovich Zakovorot,M,NaN,NaN,NaN,Russia,RUS,1900,Paris,Fencing,"Fencing Men's Sabre, Masters, Individual",NaN
2315,134198,"Walter John ""Jack"" Zealley",M,NaN,NaN,NaN,Upton Park FC,GBR,1900,Paris,Football,Football Men's Football,Gold

In [40]:
## That found the ones in the year 1900 ONLY and not the whole century
## return all the comps between 1940 and 1960

df.query("1940 <= Year <= 1960")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
36483,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Individual All-Around,Bronze
36484,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Team All-Around,Gold
36485,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Floor Exercise,NaN
36486,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Horse Vault,Gold
36487,17,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Finland,FIN,1948,London,Gymnastics,Gymnastics Men's Parallel Bars,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229422,134268,Kazimierz Zelek,M,22.0,169.0,64.0,Poland,POL,1960,Squaw Valley,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
229423,134875,Nina Alekseyevna Zhuk (Bakusheva-),F,25.0,NaN,NaN,Soviet Union-1,URS,1960,Squaw Valley,Figure Skating,Figure Skating Mixed Pairs,NaN
229424,134876,Stanislav Alekseyevich Zhuk,M,25.0,NaN,NaN,Soviet Union-1,URS,1960,Squaw Valley,Figure Skating,Figure Skating Mixed Pairs,NaN
229425,135022,Josef Egon Norbert Zimmermann,M,27.0,NaN,NaN,Austria,AUT,1960,Squaw Valley,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
229426,135376,Ross Barta Zucco,M,25.0,NaN,NaN,United States,USA,1960,Squaw Valley,Speed Skating,"Speed Skating Men's 10,000 metres",NaN

In [43]:
## Now we want to find the Black athletes during this time

df.query("Year == 1936 & NOC == 'USA'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
30008,762,"Gordon Belgum ""Gordy"" Adam",M,21.0,NaN,NaN,United States,USA,1936,Berlin,Rowing,Rowing Men's Coxed Eights,Gold
30012,829,"Morgan Orlando Adams, Jr.",M,20.0,NaN,NaN,Mystery,USA,1936,Berlin,Sailing,Sailing Mixed 6 metres,NaN
30036,1339,William Alexander (Wilhelm Alexander-) Ahlemeyer,M,29.0,NaN,NaN,United States,USA,1936,Berlin,Handball,Handball Men's Handball,NaN
30054,2387,"David Donald ""Dave"" Albritton",M,23.0,191.0,79.0,United States,USA,1936,Berlin,Athletics,Athletics Men's High Jump,Silver
30063,2552,Hugh Vincenzo Alessandroni,M,28.0,NaN,NaN,United States,USA,1936,Berlin,Fencing,"Fencing Men's Foil, Individual",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
224784,128832,"Alan Morgan ""Al"" Washbond",M,36.0,NaN,NaN,United States-1,USA,1936,Garmisch-Partenkirchen,Bobsleigh,Bobsleigh Men's Two,Gold
224785,128834,"Albert Lincoln ""Link"" Washburn",M,24.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Alpine Skiing,Alpine Skiing Men's Combined,NaN
224793,129326,Estelle D. Weigel (-Schmitt),F,21.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Figure Skating,Figure Skating Women's Singles,NaN
224794,129328,Louise E. Weigel (-Atwill),F,23.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Figure Skating,Figure Skating Women's Singles,NaN
224814,131578,"Elizabeth Davenport ""Betty"" Woolsey",F,27.0,NaN,NaN,United States,USA,1936,Garmisch-Partenkirchen,Alpine Skiing,Alpine Skiing Women's Combined,NaN

In [45]:
df.query("NOC == 'IND' and Medal == 'Gold'")

## can use & or and 
## we are looking for India when they won gold
## You have to put strings (words) in ' '

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
22082,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928,Amsterdam,Hockey,Hockey Men's Hockey,Gold
22088,2864,Richard James Allen,M,25.0,172.0,NaN,India,IND,1928,Amsterdam,Hockey,Hockey Men's Hockey,Gold
22706,19716,Dhyan Chand Bais,M,22.0,169.0,NaN,India,IND,1928,Amsterdam,Hockey,Hockey Men's Hockey,Gold
23412,39020,Michael Anthony Gateley,M,23.0,NaN,NaN,India,IND,1928,Amsterdam,Hockey,Hockey Men's Hockey,Gold
23520,41710,"William James ""Willie"" Goodsir-Cullen",M,21.0,NaN,NaN,India,IND,1928,Amsterdam,Hockey,Hockey Men's Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222916,109614,Narbu Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold
222917,109615,Pasang Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold
222918,109616,Pembra Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold
222919,109617,Sange Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold
222920,109618,Temba Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold

In [53]:
## Now we are looking for gold OR silver

india_df = df.query("NOC == 'IND'")

india_df

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
1824,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 60 metres,NaN
1825,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 100 metres,NaN
1826,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres,Silver
1827,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 110 metres Hurdles,NaN
1828,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres Hurdles,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...
263565,58899,Shiva Keshavan,M,28.0,183.0,85.0,India,IND,2010,Vancouver,Luge,Luge Men's Singles,NaN
264127,72364,Tashi Lundup,M,25.0,175.0,74.0,India,IND,2010,Vancouver,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN
264481,84450,Jamyang Namgial,M,24.0,170.0,71.0,India,IND,2010,Vancouver,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
267971,52325,Nadeem Iqbal,M,30.0,173.0,65.0,India,IND,2014,Sochi,Cross Country Skiing,Cross Country Skiing Men's 15 kilometres,NaN
270515,119471,Himanshu Thakur,M,20.0,167.0,54.0,India,IND,2014,Sochi,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN

In [55]:
india_df.query("Medal == 'Gold' or Medal == 'Silver' or Medal == 'Bronze'")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
1826,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres,Silver
1828,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres Hurdles,Silver
22082,2699,Shaukat Ali,M,30.0,NaN,NaN,India,IND,1928,Amsterdam,Hockey,Hockey Men's Hockey,Gold
22088,2864,Richard James Allen,M,25.0,172.0,NaN,India,IND,1928,Amsterdam,Hockey,Hockey Men's Hockey,Gold
22706,19716,Dhyan Chand Bais,M,22.0,169.0,NaN,India,IND,1928,Amsterdam,Hockey,Hockey Men's Hockey,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222916,109614,Narbu Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold
222917,109615,Pasang Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold
222918,109616,Pembra Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold
222919,109617,Sange Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold
222920,109618,Temba Sherpa,M,NaN,NaN,NaN,India,IND,1924,Chamonix,Alpinism,Alpinism Mixed Alpinism,Gold

In [56]:
## WOOOOOOO that worked!!!

india_df.query("Medal == 'Gold' or Medal == 'Silver' or Medal == 'Bronze'").sort_values(by="Medal")

,ID,Athlete Name,Sex,Age,Height,Weight,Team,NOC,Year,City,Sport,Event,Medal
82464,23098,Charles Cornelius,M,26.0,170.0,65.0,India,IND,1972,Munich,Hockey,Hockey Men's Hockey,Bronze
46062,53275,Khashaba Dadasaheb Jahdav,M,25.0,NaN,NaN,India,IND,1952,Helsinki,Wrestling,"Wrestling Men's Bantamweight, Freestyle",Bronze
79218,111075,Jagjit Singh Kular,M,24.0,170.0,58.0,India,IND,1968,Mexico City,Hockey,Hockey Men's Hockey,Bronze
79222,111123,Prithipal Singh,M,36.0,175.0,71.0,India,IND,1968,Mexico City,Hockey,Hockey Men's Hockey,Bronze
79225,111156,Tarsem Singh Kular,M,21.0,173.0,66.0,India,IND,1968,Mexico City,Hockey,Hockey Men's Hockey,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63008,111083,Jaswant Singh,M,29.0,185.0,77.0,India,IND,1960,Roma,Hockey,Hockey Men's Hockey,Silver
63014,111159,Udham Singh Kular,M,32.0,168.0,58.0,India,IND,1960,Roma,Hockey,Hockey Men's Hockey,Silver
63019,111173,Raghbir Singh Bhola,M,33.0,183.0,67.0,India,IND,1960,Roma,Hockey,Hockey Men's Hockey,Silver
56517,4518,"Joseph Anthony ""Joe"" Antic",M,29.0,168.0,59.0,India,IND,1960,Roma,Hockey,Hockey Men's Hockey,Silver
1826,97066,Norman Gilbert Pritchard (-Trevor),M,24.0,NaN,NaN,India,IND,1900,Paris,Athletics,Athletics Men's 200 metres,Silver

# COUNTING
## COUNTING
### COUNTING

# COUNTING

In [59]:
## Count tells you how many items of particular values exist in a dataset. 
### It doesn't care about the values themselves, just the number of entries. 

# The SUM totals the donations, items

### We use the .value_count() method:

### df_name["column_name"].value_count()

## create more cells as necessary

In [63]:
## bring in our diamonds dataset
diamonds_df = pd.read_csv("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/diamonds.csv")
diamonds_df

       carat diamond cut color clarity  depth  table  price     x     y     z
0       0.23       Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21     Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23        Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29     Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31        Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...         ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72       Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72        Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70   Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86     Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75       Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [66]:
diamonds_df["diamond cut"].nunique()

##Number of unique cuts

5

In [70]:
## What is the break down diamond_cut

diamonds_df["diamond cut"].value_counts(ascending = True)

diamond cut
Fair          1610
Good          4906
Very Good    12082
Premium      13791
Ideal        21551
Name: count, dtype: int64

In [72]:
diamonds_df["diamond cut"].value_counts(ascending = False).to_frame("Quantity")

             Quantity
diamond cut
Ideal           21551
Premium         13791
Very Good       12082
Good             4906
Fair             1610

In [74]:
## What we just did above is called Daisy chaining -- > it does all the tasks. 
## The to_frame can be added to almost anything - he suggests using it often especially when sharing work with editors

## By default, it is .value_counts(normalize = true)

# ROUND IT

round(item_to_round, number_of_decimal_places)

In [79]:
## return as percentage, rounded 2 decimal place
round(diamonds_df["diamond cut"].value_counts(normalize = True), * 100, 2)

TypeError: Value after * must be an iterable, not int

In [ ]:
#HOMEWORK CHALLENGE

## 1. how many medals were handed out in w v. s games (return both in absolutes and as a percentage)?
## 2. Top 10 count of gold medals